[checkpoint] Fix pg planner (#729)
Fix broken CI in pg_planner:
```
spmd/checkpoint/pg_planner.py:61:9: error: "init" undefined in superclass  [misc]
spmd/checkpoint/pg_planner.py:81:9: error: "init" undefined in superclass  [misc]
```

This is changed due to https://github.com/pytorch/pytorch/pull/92829.